- name: update repository index
  apt:
    update_cache: yes
    upgrade: yes
- name: Set machine timezone
  timezone:
    name: UTC

- name: Create user for application
  user:
    name: "{{application_username}}"
    update_password: on_create
    password: "!" 
    state: present
    create_home: true
    shell: /bin/bash

- name: Remove password based authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
  notify: restart sshd
