name: 'Test application'
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4
      - name: 'Set up Node v20'
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'
      - name: 'Install dependencies'
        working-directory: ./application
        run: npm ci
      - name: 'Lint code'
        working-directory: ./application
        run: npm run lint
      - name: 'Check formatting'
        working-directory: ./application
        run: npm run format:check
      - name: 'Run tests'
        working-directory: ./application
        run: npm run test
      - name: 'Build application'
        working-directory: ./application
        run: npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Prepare ssh tunnel to the server for the deployment
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.PRIVATE_SSH_KEY }}
          ssh-host: ${{ secrets.SERVER_IP }}
      - name: Pull the latest code changes
        run: ssh discord-matchmaking-bot@${{ secrets.SERVER_IP }} "cd discord-matchmaking-bot && git pull"
      - name: Stop old service
        run: ssh discord-matchmaking-bot@${{ secrets.SERVER_IP }} "systemctl stop matchmaking_bot"
      # - name: rebuild env files
      #   run: ssh discord-matchmaking-bot@${{ secrets.SERVER_IP }} "cd discord-matchmaking-bot && npm run build"
      - name: install dependencies
        run: ssh discord-matchmaking-bot@${{ secrets.SERVER_IP }} "cd discord-matchmaking-bot/application/ && npm install"
      - name: build application
        run: ssh discord-matchmaking-bot@${{ secrets.SERVER_IP }} "cd discord-matchmaking-bot/application/ && npm run build"
      - name: Start the service
        run: ssh discord-matchmaking-bot@${{ secrets.SERVER_IP }} "systemctl start matchmaking_bot"
