- name: 'Test application'
- on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master
- jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - working-directory: ./application
        - name: 'Checkout code'
          uses: actions/checkout@v4
        - name: 'Set up Node v20'
          uses: actions/setup-node@v4
          with:
            node-version: '20.10.0'
        - name: 'Install dependencies'
          run: npm install
        - name: 'Lint code'
          run: npm run lint
        - name: 'Check formatting'
          run: npm run format:check
        - name: 'Run tests'
          run: npm run test
        - name: 'Build application'
          run: npm run build
